// Generated by tools/export_controls.py. Do not edit.
//
// The reference registry's bounds for the controls this core resolves.
// tools/export_controls.py --check fails the gate when this file and
// Contracts/catalogues/world-controls-v1.json disagree, so a divergence becomes a
// failing build rather than a core that refuses what the reference accepts.

{"amplitude",{0.,10000000.}},
{"belt_width",{0.01,0.3}},
{"crust_bias",{-1.,1.}},
{"culture_link_cost",{1.,100000.}},
{"erosion_passes",{0.,40.}},
{"erosion_strength",{0.,1.}},
{"extent",{0.01,10000000.}}, // native-only: no reference row
{"globe_radius",{0.01,10000000.}},
{"moisture_bias",{-1.,1.}},
{"mountain_detail",{0.,1.}},
{"octaves",{1.,10.}},
{"orogeny",{0.,20.}},
{"plate_count",{3.,48.}},
{"radius",{0.01,10000000.}},
{"ridge",{0.,1.}},
{"river_threshold_km2",{0.001,10000.}},
{"sea_level",{-10000000.,10000000.}},
{"settlement_spacing",{10.,100000.}},
{"support_reach",{100.,100000.}},
{"tectonic_relief",{0.,10000000.}},
{"temperature_offset",{-40.,40.}},
{"wavelength",{0.01,10000000.}},
